# Generated by Django 2.2.5 on 2022-03-25 12:09
import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20220221_1825"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                default="Unnamed User",
                max_length=30,
                verbose_name="first name",
            ),
        ),
    ]
